import type { ResourceKind } from '@devops-platform/games';
import {
  Hexagon,
  PanelsTopLeft,
  Layers3,
  LibraryBig,
  Orbit,
  BadgeCheck,
  AlarmClock,
  Scaling,
  ShieldCheck,
  Network,
  Route,
  ShieldBan,
  FileSliders,
  LockKeyhole,
  ContactRound,
  KeyRound,
  Link2,
  ShieldUser,
  Workflow,
  DatabaseZap,
  Database,
  HardDrive,
  Scan,
  Gauge,
  SlidersHorizontal,
  Server,
  type LucideIcon,
} from 'lucide-react';

/** Each resource has its own silhouette, even when its tool is unavailable. */
export const RESOURCE_ICON = {
  Pod: Hexagon,
  Deployment: PanelsTopLeft,
  ReplicaSet: Layers3,
  StatefulSet: LibraryBig,
  DaemonSet: Orbit,
  Job: BadgeCheck,
  CronJob: AlarmClock,
  HorizontalPodAutoscaler: Scaling,
  PodDisruptionBudget: ShieldCheck,
  Service: Network,
  Ingress: Route,
  NetworkPolicy: ShieldBan,
  ConfigMap: FileSliders,
  Secret: LockKeyhole,
  ServiceAccount: ContactRound,
  Role: KeyRound,
  RoleBinding: Link2,
  ClusterRole: ShieldUser,
  ClusterRoleBinding: Workflow,
  PersistentVolumeClaim: DatabaseZap,
  PersistentVolume: Database,
  StorageClass: HardDrive,
  Namespace: Scan,
  ResourceQuota: Gauge,
  LimitRange: SlidersHorizontal,
  Node: Server,
} satisfies Record<ResourceKind, LucideIcon>;
